# Site settings
title: Sami Singh | httpster.io
description: Sami Singh | httpster.io
# baseurl: ""
url: "http://httpster.io" 
host: 0.0.0.0
port: 80
# User settings
username: Sami Singh
user_title: Meikon tuleva UX-velho
email: sami@httpster.io
twitter_username: httpsterio
github_username:  httpsterio

# Google-analytics
google-analytics:
  id: "UA-97091351-1"

exclude: ['package.json', 'src' , 'node_modules']
